name: DevSecOps Optimized Pipeline

on:
  pull_request: {branches: [main]}
  push: {branches: [main]}

jobs:
  # Job 1: Scan
  quality-and-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - name: Lint & Audit
        run: |
          npm run lint
          npm audit --audit-level=high
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7

  # Job 2: Deploy (Harus ada di bawah 'jobs:')
  deploy:
    needs: quality-and-security
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: .vercel
          key: ${{ runner.os }}-vercel-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npx @cloudflare/next-on-pages@1
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'artup'
          directory: '.vercel/output/static'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}